title: 'sample site'
url: ''
baseurl: ''
permalink: 'pretty'

search:
  main:
    index: 'js/lunr-index.json'
    collections:
      csv_collection:
        fields: ['gambrel', 'blasphemous']
      json_collection:
        fields: ['gambrel', 'blasphemous']
      yaml_collection:
        fields: ['gambrel', 'blasphemous']
      page_collection:
        content: true
